# Generated by Django 3.2.25 on 2024-11-04 17:30

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('description_1', ckeditor.fields.RichTextField(verbose_name='Описание_1')),
                ('description_2', ckeditor.fields.RichTextField(verbose_name='Описание_2')),
                ('image', models.ImageField(default='', upload_to='image1', verbose_name='Изображения')),
                ('date_1', models.DateField(default=datetime.datetime.now, verbose_name='Дата тура_1')),
                ('date_2', models.DateField(default=datetime.datetime.now, verbose_name='Дата тура_2')),
                ('date_3', models.DateField(default=datetime.datetime.now, verbose_name='Дата тура_3')),
                ('date_4', models.DateField(default=datetime.datetime.now, verbose_name='Дата тура_4')),
                ('price_ank', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена взрослый')),
                ('price_child', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена ребенок')),
                ('program', ckeditor.fields.RichTextField(default=None, verbose_name='Программа тура')),
                ('includeprice', models.TextField(default=None, verbose_name='В стоимость включено')),
                ('not_includeprice', ckeditor.fields.RichTextField(default=None, verbose_name='В стоимость не включено')),
                ('pamiatka', ckeditor.fields.RichTextField(default=None, verbose_name='Памятка туристу')),
                ('type', models.CharField(choices=[('PERM', 'Туры по Пермскому краю'), ('URAL', 'Туры по Уралу'), ('ACT', 'Активный отдых'), ('CHILD', 'Экскурсии для детей')], default='PERM', max_length=5, verbose_name='Тип')),
            ],
        ),
    ]
