# Generated by Django 3.2.25 on 2024-11-04 18:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turistsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytour',
            name='description_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание_1'),
        ),
    ]
