# Generated by Django 3.2.25 on 2024-11-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistsite', '0002_alter_mytour_description_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytour',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
