# Generated by Django 3.2.25 on 2024-11-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistsite', '0004_mytour_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytour',
            name='image_1',
            field=models.ImageField(default='strelka.jpg', upload_to='image1', verbose_name='Изображения'),
        ),
    ]
