# Generated by Django 3.2.25 on 2024-11-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistsite', '0007_auto_20241108_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytour',
            name='description_1',
            field=models.TextField(verbose_name='Описание_1'),
        ),
        migrations.AlterField(
            model_name='mytour',
            name='image_1',
            field=models.ImageField(default='', upload_to='image1', verbose_name='Изображения'),
        ),
    ]
