# Generated by Django 3.2.25 on 2024-11-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistsite', '0010_remove_mytour_image_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytour',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер тура'),
        ),
    ]
