# Generated by Django 3.2.25 on 2024-11-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistsite', '0012_alter_mytour_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytour',
            name='title',
            field=models.TextField(max_length=120, verbose_name='Название'),
        ),
    ]
