# Generated by Django 3.2.25 on 2024-11-26 14:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turistsite', '0020_alter_booking_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(default=' ', max_length=50, verbose_name='Фамилия')),
                ('col_of_ank', models.IntegerField(default=0)),
                ('col_of_child', models.IntegerField(default=0)),
                ('price_ank', models.IntegerField(default=0)),
                ('price_child', models.IntegerField(default=0)),
                ('checkin_date', models.DateField(choices=[('date_1', 'date_1'), ('date_2', 'date_2'), ('date_3', 'date_3'), ('date_4', 'date_4')], default=datetime.datetime.now)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('title_of_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turistsite.mytour', verbose_name='Название тура')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
