# Generated by Django 3.2.25 on 2024-11-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistsite', '0023_auto_20241129_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking1',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
    ]
